# Generated by Django 2.0.3 on 2020-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('reg', 'Regular'), ('sic', 'Sicilian')], max_length=50),
        ),
    ]
