# Generated by Django 2.0.3 on 2020-03-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200312_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dinner_platters',
            field=models.ManyToManyField(blank=True, to='orders.DinnerPlatters'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pasta',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pizza',
            field=models.ManyToManyField(blank=True, to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='salads',
            field=models.ManyToManyField(blank=True, to='orders.Salads'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sub_add_on',
            field=models.ManyToManyField(blank=True, to='orders.SubAddOn'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='subs',
            field=models.ManyToManyField(blank=True, to='orders.Subs'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='topping',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
